# Generated by Django 5.1.4 on 2025-02-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True, verbose_name='Season Year')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=255, verbose_name='Stadium Name')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, unique=True, verbose_name='Team Name')),
            ],
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='Match Date')),
                ('match_referee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Match Referee')),
                ('umpire1', models.CharField(max_length=255, verbose_name='Umpire 1')),
                ('umpire2', models.CharField(max_length=255, verbose_name='Umpire 2')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_analysis.season')),
                ('match_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_city', to='ipl_analysis.stadiuminfo', verbose_name='Match City')),
                ('match_stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipl_analysis.stadiuminfo', verbose_name='Match Stadium')),
                ('match_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipl_analysis.team', verbose_name='Match Winner')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_associations', to='ipl_analysis.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team_associations', to='ipl_analysis.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_associations', to='ipl_analysis.team')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'season'], name='ipl_analysi_player__da10cf_idx'), models.Index(fields=['team', 'season'], name='ipl_analysi_team_id_e87446_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'team', 'season'), name='unique_player_team_season')],
            },
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home_team', models.BooleanField(default=False, verbose_name='Is Home Team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='ipl_analysis.matchinfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_analysis.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'team'), name='unique_match_team')],
            },
        ),
        migrations.AddIndex(
            model_name='matchinfo',
            index=models.Index(fields=['match_date'], name='ipl_analysi_match_d_a252bf_idx'),
        ),
        migrations.AddIndex(
            model_name='matchinfo',
            index=models.Index(fields=['season'], name='ipl_analysi_season__0dbb62_idx'),
        ),
    ]
